project:
  type: book

book:
  title: "ESR-Technical-Documentation"
  author: "Greg Williams, Chris Dailey, etc"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - Introduction.qmd
    - HabitatCompressionIndex.qmd
    - SnowWaterEquivalent.qmd
    - MaximumStreamTemperature.qmd
    - Streamflow
    - NCCForage


format:
  html:
    theme: cosmo
 


editor: visual

