project:
  type: book

book:
  title: "ESR-Technical-Documentation"
  author: "Greg Williams, Chris Dailey, etc"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - Introduction.qmd



format:
  html:
    theme: cosmo
 


editor: visual

