project:
  type: book

book:
  title: "ESR-Technical-Documentation"
  author: "Greg Williams, Chris Dailey, etc"
  date: "11/05/2024"
  chapters:
    - index.qmd
    - Introduction.qmd
    - BasinScaleIndicators.qmd
    - MarineHeatwaves.qmd
    - Upwelling.qmd
    - HabitatCompressionIndex.qmd
    - DissolvedOxygen.qmd
    - OceanAcidification.qmd
    - FreshwaterHabitat.qmd
    - SnowWaterEquivalent.qmd
    - MaximumStreamTemperature.qmd
    - Streamflow.qmd
    - Copepods.qmd
    - Krill.qmd
    - DungenessCrabMegalopae.qmd
    - NCCForage.qmd
    - CCCForage.qmd
    - SCCForage.qmd


format:
  html:
    theme: cosmo
    
bibliography: esr-bibliography.bib
 

editor: visual

