project:
  type: book

book:
  title: "ESR-Technical-Documentation"
  author: "Greg Williams, Chris Dailey, etc"
  date: "11/05/2024"
  chapters:
    - index.qmd
    - Introduction.qmd
    - part: Climate and Oceans
      chapters:
      - BasinScaleIndicators.qmd
      - MarineHeatwaves.qmd
      - SnowWaterEquivalent.qmd
      - MaximumStreamTemperature.qmd
      - Streamflow.qmd
      - DissolvedOxygen.qmd
      - OceanAcidification.qmd
      - FreshwaterHabitat.qmd
      - Upwelling.qmd
      - HabitatCompressionIndex.qmd
    - part: Focal Components of Ecological Integrity
      chapters:
      - Copepods.qmd
      - Krill.qmd
      - DungenessCrabMegalopae.qmd
      - NCCForage.qmd
      - CCCForage.qmd
      - SCCForage.qmd
    
   
   
    
   
    
   


format:
  html:
    theme: cosmo
    
bibliography: esr-bibliography.bib
 

editor: visual

