project:
  type: book

book:
  title: "ESR-Technical-Documentation"
  author: "Greg Williams, Chris Dailey, etc"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - Introduction.qmd
    - Upwelling.qmd
    - MarineHeatwaves.qmd
    - HabitatCompressionIndex.qmd
    - DissolvedOxygen.qmd
    - OceanAcidification.qmd
    - FreshwaterHabitat.qmd
    - SnowWaterEquivalent.qmd
    - MaximumStreamTemperature.qmd
    - Streamflow.qmd
    - NCCForage.qmd
    - CCCForage.qmd
    - SCCForage.qmd


format:
  html:
    theme: cosmo
 


editor: visual

