# CPS Survey

Acoustic-trawl method (ATM) surveys have been used by the NOAA Southwest Fisheries Science Center in most years since 2006 to map the distributions and estimate the abundances of coastal pelagic fish species (CPS) in the coastal region from Vancouver Island, Canada, to San Diego, California (e.g., Zwolinski et al. 2014). In 2021 and 2022, the surveys were expanded to include portions of Baja California, Mexico (Stierhoff et al. 2023a, Stierhoff et al. 2023b). The surveys cover waters to at least the 1,000-fathom (1829-m) isobath, or 65 km from shore. The five most abundant CPS in this domain are Northern Anchovy, Pacific Herring, Pacific Sardine, Jack Mackerel, and Pacific Mackerel. The biomass of Pacific Sardine is calculated separately for the northern and southern stocks based on oceanographic habitat, spatial separation, and demographic structure (Zwolinski and Demer 2023). The ATM combines data from echosounders, which record CPS echoes, and trawls, which produce information about the composition, sizes, and ages of the fishes. This survey also samples the densities of CPS eggs at 3-m depth using a continuous underway fish egg sampler (CUFES) mounted on the ship’s hull.