# Juvenile Groundfish Abundance

Yearly indices of the abundances of juvenile sablefish, Dover sole, shortspine thornyhead, and longspine thornyhead along the West Coast were calculated using species distribution models. The analysis follows the general approach used by Tolimieri et al. (2020), which was reviewed by the SSC-ES in September 2021, but this update uses the sdmTMB modeling package (Anderson et al. 2022) instead of the VAST package (Thorson 2019). The sdmTMB approach is being used by many West Coast groundfish stock assessment biologists to assimilate survey data, and was reviewed favorably by the SSC-Groundfish Subcommittee in summer of 2022 (PFMC 2022c).

Data for indicators come from the West Coast Groundfish Bottom Trawl Survey (WCGBTS) (Keller et al. 2017) for 2003-2021. There are no data for 2020 because the WCGBTS was canceled due to the COVID-19 pandemic. 
The survey data includes estimates of age, length, and biomass for subsamples of each haul, and occasionally for the entire haul when catch is low. Length is measured (cm total length) for all individuals in the subsample, but many individual fishes lack weight or age data due to time constraints in the field and ageing lab. To expand the subsample, individuals with length data only were given estimated weights based on species-specific length-weight relationships. Individual fish were allocated to age classes following Tolimieri et al. (2020) by using length-age relationships from the WCGBTS data to determine age-class maximum lengths (Table K.1). The proportional biomass of juveniles in each subsample was calculated and then used to extrapolate total estimated juvenile fish biomass in the full trawl. See Tolimieri et al. (2020) for more detail.

[insert: Table K.1: Length, age, and depth range information for juvenile size/age classes of groundfish in this analysis. The trawl data do not contain ages for the thornyheads.]

Coastwide juvenile groundfish abundances were estimated using a spatially explicit, species distribution model evaluated with the sdmTMB package in R. The response variable was CPUE quantified as kg of juveniles per km2. The models included one common intercept across years, and spatial and spatiotemporal random fields, with anisotropy to account for different rates of autocorrelation with latitude versus longitude (~ depth). The common intercept prevents the model from forcing biomass to increase or decrease coastwide in a given year (thereby potentially overestimating recruitment in some areas) as would be the case for yearly intercept. Depth was scaled and included to account for differences in density across depths. To avoid projecting to areas with zero biomass, the depth range of the data used for each species in the analysis was restricted based on the distribution of positive biomass observations (Table K.1). Again, the values used here follow Tolimieri et al. (2020) with the exception that the lower depth limit for sablefish was set to 250 m, which encompasses more than 99% of their observed juvenile biomass. Pass was included as a fixed factor (as a proxy for time of year; the WCGBTS conducts two coastwide passes each year, in May-July and August-October). Models were fit with a delta-gamma distribution to account for the prevalence of zeros in the data, and the mesh was set to 10 km, resulting in 650-800 knots depending upon species. Model fits were then extrapolated to a 2x2 km grid of the West Coast to estimate total abundance in kg for juveniles in a given year. For some species, it was necessary to combine age or size classes to obtain enough data for models to converge (Table K.1). The resulting biomass estimate was converted to an index scaled between 0-1 by dividing all values by the greatest upper 95% confidence limit in the time series. Finally, we also evaluated different error distributions, including Tweedie and delta-Poisson-link-gamma (used in Tolimieri et al 2020). Based on examination of the residuals, the delta-gamma distribution was chosen as the most appropriate error distribution.

To address previous suggestions by the SSC-ES, we also evaluated models with year included as a fixed factor or allowed year to have a random intercept. When included as a fixed factor, models failed to converge likely due to identifiability problems due to also including the spatiotemporal random field. For sablefish and Dover sole, inclusion of year with a random intercept also created fit problems leading to very large standard errors for some estimated parameters. Therefore, we excluded the term from the final models.
