# Marine Heatwaves

There is growing recognition that marine heatwaves can have strongly disruptive impacts on the CCE (e.g., Morgan et al. 2019). Based on an analysis of sea surface temperature anomalies (SSTa) obtained from satellite measurements (OISST; we define marine heatwaves as 1) times when normalized SSTa \>1.29 s.d. (90th percentile) of the long-term SSTa time series at a location, and 2) lasts for \>5 days; which are analogous to the thresholds suggested in Hobday et al. (2016). Here, we further report on statistics concerning large heatwaves (LHW) which were tracked through space and time, with LHW defined as those heatwaves with an area \> 400,000 km2 (these denote the top 20% of all heatwaves by area as measured since 1982 when satellite data became available for tracking; Leising, in revision).

# Need to work in climatology from this Note: the underlying climatology used for SST anomaly analysis has changed from 1982-2010, to now encompass 1982-2020; hence small changes in the retrospective analysis of tracked heatwaves reported more recently as compared to previous reports.
