<<<<<<< Updated upstream
=======
---
lightbox: true
bibliography: esr-bibliography.bib
format:
 html:
  code-fold: true
---


```{r}
cciea_yr <- 2024

ds_id <- 'cciea_OC_NPH'	   
ts_id_list = list('cciea_OC_NPH')
source("script_IDS.R")
ds_id_nph <- ds_id
vec2_nph <- vec2
ds_id_lbl_nph <- ds_id_lbl
rgn_lbl_nph <- rgn_lbl

ds_id <- 'cciea_OC_NPH_Jan_Feb'	   
ts_id_list = list('cciea_OC_NPH_JF')
source("script_IDS.R")
ds_id_jf <- ds_id
vec2_jf <- vec2
ds_id_lbl_jf <- ds_id_lbl
rgn_lbl_jf <- rgn_lbl



```

>>>>>>> Stashed changes

# North Pacific High Indicators

**Description** Variations in the areal extent of the North Pacific High (NPH) during the winter is predictive of winter upwelling. The January and February average of the NPH area can be used as a "preconditioning" index for ecosystem responses in the spring.

**Indicator Category**     `{r} vec2_nph[['Component_Section']]`

**Data Steward**     `{r} vec2_nph[['PI']]`

**Erddap Dataset ID**     `{r} ds_id_jf`, `{r} ds_id_nph`

**CCIEA timeseries ID**     `{r} ds_id_lbl_jf`, `{r} ds_id_lbl_nph`

**Region**     `{r} rgn_lbl_jf`, `{r} rgn_lbl_nph`

**Public availability statement**     Source data are publicly available.

**Data sources**   &nbsp The U.S. Navy Fleet Numerical Meteorology and Oceanography Center (FNMOC) to take advantage of the Navy's global oceanographic and meteorological databases. FNMOC produces operational forecasts of the state of the atmosphere and the ocean several times daily and maintains archives of several important parameters, such as sea level pressure and temperature. The NPH area is derived from FNMOC Sea Level Pressure (SLP) monthly means. The SLP data are available at <https://upwell.pfeg.noaa.gov/erddap/griddap/erdlasFnWPr.html>.

**Additional Information**   &nbsp During the winter, periods of upwelling or, farther north, reduced downwelling can limit stratification and facilitate introduction of nutrients to the surface, acting to precondition the ecosystem for increased production in the spring [@schroeder2009; @black2010]. The area of sea level pressure associated with the North Pacific High (NPH) can be used as an index of this winter preconditioning [@schroeder2013].

**Figures**

**References**
